feat(elastic-jupyter): Add chart
tkestack/charts pull request #49
Opened 2021-06-17 08:46 UTC by gaocegege

Signed-off-by: cegao <cegao@tencent.com>

2021-06-18 06:21 UTC, xieydd requested changes

2021-06-18 06:21 UTC, xieydd commented on incubator/elastic-jupyter-operator-on-tke/Chart.yaml
> +icon: https://github.com/tkestack/charts/raw/main/icons/mpi-operator-on-tke.png
change icon from mpi-operator to elastic-jupyter.

2021-06-18 06:39 UTC, gaocegege commented on incubator/elastic-jupyter-operator-on-tke/Chart.yaml
> +icon: https://github.com/tkestack/charts/raw/main/icons/mpi-operator-on-tke.png
Fixed, PTAL

2021-06-21 02:32 UTC, gaocegege commented
/assign @huxiaoliang

2021-06-21 07:34 UTC, merged